### PR TITLE
Bugfix/issue 20 error in on deck

### PR DESCRIPTION
**Pull request by thesoftwarejedi**
fixes on deck issue

### CODE REVIEW

**Comment by OverloadUT** [comment]
Any idea why item might be null in that case? It's a good idea to get this error handling in there, but I'm concerned about why it would ever iterate in to a null instance of item.

Could you log the output of what ```items``` is in the case that causes an error so I can see what's up?

**Comment by thesoftwarejedi** [comment]
Yeah, I can take a look. Seems crazy to me too, that's why I just got past it. Third party API can be a pain. I'll get to logging it out as soon as I can.

**Comment by OverloadUT** [comment]
Update: it turns out that the issue causing this was quite simple: movies! I did not have any movies in my library, and now that I do I can see that's what was causing it. Movies have no grandparent, so an `undefined` was getting passed to the list building function. I have implemented a fix to this in a different way so that movies actually work - I'll link it here once I push it up to github!

**Comment by OverloadUT** [comment]
Fixed in latest commit!

**Pull request closed without merging**
